name: Xcode Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-for-ios:
    strategy:
      matrix:
        configuration: [ Release, Debug ]
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: maxim-lobanov/setup-xcode@v1
        name: Setup Xcode
        with:
          xcode-version: 15.1  # 15.4 may crash

      - name: Build for iOS
        run: |
          xcodebuild clean build \
            -project LLMFarm.xcodeproj \
            -scheme LLMFarm_Release clean archive -configuration ${{ matrix.configuration }} \
            -archivePath LLMFarm.xcarchive \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: XCarchive to ipa
        run: |
          mkdir Payload
          cp -a LLMFarm.xcarchive/Products/Applications/* Payload
          zip -rmq "LLMFarm-${{ matrix.configuration }}.ipa" Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-${{ matrix.configuration }}
          path: |
            LLMFarm-${{ matrix.configuration }}.ipa

  build-for-macos:
    strategy:
      matrix:
        configuration: [ Release, Debug ]
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: maxim-lobanov/setup-xcode@v1
        name: Setup Xcode
        with:
          xcode-version: 15.1  # 15.4 may crash

      - name: Build
        run: |
          xcodebuild clean build \
            -project LLMFarm.xcodeproj \
            -scheme LLMFarm_Release clean archive \
            -configuration ${{ matrix.configuration }} \
            -archivePath LLMFarm.xcarchive \
            -sdk macosx \
            -arch x86_64 \
            -arch arm64 \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY=""

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-${{ matrix.configuration }}
          path: |
            LLMFarm.xcarchive/Products/Applications